// ==========================================================================
// 📖 华文智能互动学习阅读器 - 词汇数据库 (data.js)
// ==========================================================================

const lessonTitle = "风雨送餐路";

const lessonData = [
    // ===== 第1段 =====
    ["清晨", "qīng chén", "early morning", "awal pagi"],
    ["五点", "wǔ diǎn", "five o'clock", "pukul lima"],
    ["闹钟", "nào zhōng", "alarm clock", "jam loceng"],
    ["准时", "zhǔn shí", "on time", "tepat masa"],
    ["响起", "xiǎng qǐ", "rings", "berbunyi"],
    ["。", "", "", ""],
    ["阿力", "ā lì", "Ah Li", "Ah Li"],
    ["睁开眼睛", "zhēng kāi yǎn jīng", "open eyes", "membuka mata"],
    ["，", "", "", ""],
    ["望着", "wàng zhe", "looking at", "memandang"],
    ["天花板", "tiān huā bǎn", "ceiling", "siling"],
    ["，", "", "", ""],
    ["沉重", "chén zhòng", "heavily", "berat"],
    ["地", "de", "", ""],
    ["吐", "tǔ", "exhale", "hembus"],
    ["出", "chū", "out", "keluar"],
    ["一口气", "yī kǒu qì", "a breath", "satu nafas"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第2段

    // ===== 第2段 =====
    ["三个月", "sān gè yuè", "three months", "tiga bulan"],
    ["前", "qián", "ago", "dahulu"],
    ["，", "", "", ""],
    ["工厂", "gōng chǎng", "factory", "kilang"],
    ["裁员", "cái yuán", "layoffs", "pemberhentian pekerja"],
    ["，", "", "", ""],
    ["他", "tā", "he", "dia"],
    ["也", "yě", "also", "juga"],
    ["收到", "shōu dào", "received", "menerima"],
    ["了", "le", "", ""],
    ["公司", "gōng sī", "company", "syarikat"],
    ["给", "gěi", "gave", "memberi"],
    ["他", "tā", "him", "dia"],
    ["的", "de", "", ""],
    ["那封", "nà fēng", "that", "itu"],
    ["信", "xìn", "letter", "surat"],
    ["。", "", "", ""],
    ["他", "tā", "he", "dia"],
    ["没有", "méi yǒu", "did not", "tidak"],
    ["把", "bǎ", "", ""],
    ["消息", "xiāo xī", "news", "berita"],
    ["立刻", "lì kè", "immediately", "segera"],
    ["告诉", "gào su", "tell", "memberitahu"],
    ["妻子", "qī zi", "wife", "isteri"],
    ["，", "", "", ""],
    ["而是", "ér shì", "but rather", "tetapi"],
    ["等到", "děng dào", "wait until", "tunggu sehingga"],
    ["晚饭", "wǎn fàn", "dinner", "makan malam"],
    ["后", "hòu", "after", "selepas"],
    ["，", "", "", ""],
    ["一家人", "yī jiā rén", "whole family", "sekeluarga"],
    ["围坐", "wéi zuò", "sit around", "duduk mengelilingi"],
    ["在", "zài", "at", "di"],
    ["桌前", "zhuō qián", "table", "meja"],
    ["时", "shí", "when", "apabila"],
    ["，", "", "", ""],
    ["才", "cái", "only then", "barulah"],
    ["从", "cóng", "from", "dari"],
    ["公事包", "gōng shì bāo", "briefcase", "beg kerja"],
    ["里", "lǐ", "in", "dalam"],
    ["拿出", "ná chū", "take out", "mengeluarkan"],
    ["那封信", "nà fēng xìn", "that letter", "surat itu"],
    ["，", "", "", ""],
    ["像", "xiàng", "like", "seperti"],
    ["扔出", "rēng chū", "throw out", "melontar"],
    ["一颗", "yī kē", "a", "satu"],
    ["震撼弹", "zhèn hàn dàn", "shock bomb", "bom kejutan"],
    ["。", "", "", ""],
    ["妻子", "qī zi", "wife", "isteri"],
    ["的", "de", "", ""],
    ["筷子", "kuài zi", "chopsticks", "penyepit"],
    ["停", "tíng", "stopped", "berhenti"],
    ["在", "zài", "in", "di"],
    ["半空", "bàn kōng", "mid-air", "di udara"],
    ["，", "", "", ""],
    ["孩子", "hái zi", "child", "anak"],
    ["的", "de", "", ""],
    ["眼睛", "yǎn jīng", "eyes", "mata"],
    ["瞪大", "dèng dà", "widened", "terbeliak"],
    ["了", "le", "", ""],
    ["。", "", "", ""],
    ["那", "nà", "that", "itu"],
    ["一晚", "yī wǎn", "that night", "malam itu"],
    ["，", "", "", ""],
    ["饭桌", "fàn zhuō", "dining table", "meja makan"],
    ["上", "shàng", "on", "atas"],
    ["的", "de", "", ""],
    ["气氛", "qì fēn", "atmosphere", "suasana"],
    ["沉重", "chén zhòng", "heavy", "berat"],
    ["得", "de", "", ""],
    ["像", "xiàng", "like", "seperti"],
    ["压", "yā", "pressed", "menekan"],
    ["了", "le", "", ""],
    ["一块", "yī kuài", "a", "satu"],
    ["大石", "dà shí", "big stone", "batu besar"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第3段

    // ===== 第3段 =====
    ["那", "nà", "That", "Itu"],
    ["是", "shì", "is", "ialah"],
    ["他", "tā", "his", "dia"],
    ["人生", "rén shēng", "life", "kehidupan"],
    ["中", "zhōng", "in", "dalam"],
    ["一场", "yī chǎng", "a", "satu"],
    ["没有", "méi yǒu", "no", "tiada"],
    ["硝烟", "xiāo yān", "gunpowder smoke", "asap mesiu"],
    ["的", "de", "", ""],
    ["战争", "zhàn zhēng", "war", "peperangan"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第4段

    // ===== 第4段 =====
    ["长长", "cháng cháng", "long", "panjang"],
    ["的", "de", "", ""],
    ["账单", "zhàng dān", "bills", "bil"],
    ["摆", "bǎi", "placed", "diletakkan"],
    ["在", "zài", "on", "di"],
    ["桌上", "zhuō shàng", "table", "meja"],
    ["：", "", "", ""],
    ["房租", "fáng zū", "rent", "sewa rumah"],
    ["、", "", "", ""],
    ["水电", "shuǐ diàn", "utilities", "air dan elektrik"],
    ["、", "", "", ""],
    ["孩子", "hái zi", "child's", "anak"],
    ["的", "de", "", ""],
    ["学费", "xué fèi", "school fees", "yuran sekolah"],
    ["、", "", "", ""],
    ["老人", "lǎo rén", "elderly", "orang tua"],
    ["的", "de", "", ""],
    ["医药费", "yī yào fèi", "medical fees", "yuran perubatan"],
    ["……", "", "", ""],
    ["每", "měi", "every", "setiap"],
    ["一张", "yī zhāng", "one", "satu"],
    ["都", "dōu", "all", "semua"],
    ["像", "xiàng", "like", "seperti"],
    ["一根", "yī gēn", "a", "sebatang"],
    ["针", "zhēn", "needle", "jarum"],
    ["，", "", "", ""],
    ["扎", "zhā", "pierce", "menusuk"],
    ["在", "zài", "in", "di"],
    ["他", "tā", "his", "dia"],
    ["的", "de", "", ""],
    ["心头", "xīn tóu", "heart", "hati"],
    ["。", "", "", ""],
    ["他", "tā", "his", "dia"],
    ["眉头", "méi tóu", "brows", "kening"],
    ["上", "shàng", "on", "atas"],
    ["岁月", "suì yuè", "years", "usia"],
    ["的", "de", "", ""],
    ["印记", "yìn jì", "marks", "kesan"],
    ["，", "", "", ""],
    ["仿佛", "fǎng fú", "as if", "seolah-olah"],
    ["又", "yòu", "again", "lagi"],
    ["增添", "zēng tiān", "added", "menambah"],
    ["了", "le", "", ""],
    ["几道", "jǐ dào", "a few", "beberapa"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第5段

    // ===== 第5段 =====
    ["思前想后", "sī qián xiǎng hòu", "think over", "fikir masak-masak"],
    ["，", "", "", ""],
    ["他", "tā", "he", "dia"],
    ["终于", "zhōng yú", "finally", "akhirnya"],
    ["做出", "zuò chū", "made", "membuat"],
    ["了", "le", "", ""],
    ["决定", "jué dìng", "decision", "keputusan"],
    ["。", "", "", ""],
    ["第二天", "dì èr tiān", "next day", "hari berikutnya"],
    ["，", "", "", ""],
    ["他", "tā", "he", "dia"],
    ["戴起", "dài qǐ", "put on", "memakai"],
    ["头盔", "tóu kuī", "helmet", "topi keledar"],
    ["，", "", "", ""],
    ["骑上", "qí shàng", "ride on", "menunggang"],
    ["摩托车", "mó tuō chē", "motorcycle", "motosikal"],
    ["，", "", "", ""],
    ["开始", "kāi shǐ", "started", "mula"],
    ["了", "le", "", ""],
    ["外送员", "wài sòng yuán", "delivery rider", "penghantar makanan"],
    ["的", "de", "", ""],
    ["生活", "shēng huó", "life", "kehidupan"],
    ["。", "", "", ""],
    ["他", "tā", "his", "dia"],
    ["的", "de", "", ""],
    ["任务", "rèn wù", "task", "tugas"],
    ["，", "", "", ""],
    ["是", "shì", "is", "ialah"],
    ["让", "ràng", "let", "membuat"],
    ["门户", "mén hù", "households", "rumah"],
    ["及时", "jí shí", "in time", "tepat pada masanya"],
    ["吃上", "chī shàng", "eat", "makan"],
    ["热腾腾", "rè téng téng", "steaming hot", "panas menggelegak"],
    ["美食", "měi shí", "delicious food", "makanan lazat"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第6段

    // ===== 第6段 =====
    ["奔波", "bēn bō", "rushing about", "berulang-alik"],
    ["成", "chéng", "became", "menjadi"],
    ["了", "le", "", ""],
    ["他", "tā", "his", "dia"],
    ["生活", "shēng huó", "life", "kehidupan"],
    ["的", "de", "", ""],
    ["常态", "cháng tài", "norm", "kebiasaan"],
    ["。", "", "", ""],
    ["阳光明媚", "yáng guāng míng mèi", "bright sunshine", "cahaya matahari cerah"],
    ["时", "shí", "when", "apabila"],
    ["，", "", "", ""],
    ["他", "tā", "he", "dia"],
    ["无惧", "wú jù", "fearless", "tidak takut"],
    ["骄阳", "jiāo yáng", "scorching sun", "matahari terik"],
    ["的", "de", "", ""],
    ["炽烈", "chì liè", "intense heat", "kepanasan terik"],
    ["；", "", "", ""],
    ["疾风骤雨", "jí fēng zhòu yǔ", "strong wind and sudden rain", "angin kencang dan hujan lebat"],
    ["时", "shí", "when", "apabila"],
    ["，", "", "", ""],
    ["他", "tā", "he", "dia"],
    ["无畏", "wú wèi", "fearless", "tidak gentar"],
    ["风雨", "fēng yǔ", "wind and rain", "angin dan hujan"],
    ["的", "de", "", ""],
    ["猛烈", "měng liè", "fierce", "ganas"],
    ["。", "", "", ""],
    ["无论", "wú lùn", "no matter", "tidak kira"],
    ["晴天", "qíng tiān", "sunny day", "hari cerah"],
    ["雨天", "yǔ tiān", "rainy day", "hari hujan"],
    ["，", "", "", ""],
    ["他", "tā", "he", "dia"],
    ["依旧", "yī jiù", "still", "masih"],
    ["挺直", "tǐng zhí", "straighten", "meluruskan"],
    ["背脊", "bèi jǐ", "back", "tulang belakang"],
    ["，", "", "", ""],
    ["穿梭", "chuān suō", "shuttle", "berulang-alik"],
    ["于", "yú", "in", "di"],
    ["车水马龙", "chē shuǐ mǎ lóng", "heavy traffic", "lalu lintas sesak"],
    ["的", "de", "", ""],
    ["大街", "dà jiē", "main street", "jalan besar"],
    ["和", "hé", "and", "dan"],
    ["小巷", "xiǎo xiàng", "alleys", "lorong"],
    ["。", "", "", ""],
    ["他", "tā", "he", "dia"],
    ["把", "bǎ", "", ""],
    ["食物保温袋", "shí wù bǎo wēn dài", "food thermal bag", "beg makanan panas"],
    ["里", "lǐ", "in", "dalam"],
    ["的", "de", "", ""],
    ["餐食", "cān shí", "meal", "makanan"],
    ["，", "", "", ""],
    ["兢兢业业", "jīng jīng yè yè", "conscientiously", "dengan tekun"],
    ["、", "", "", ""],
    ["稳当", "wěn dāng", "steadily", "dengan stabil"],
    ["地", "de", "", ""],
    ["送达", "sòng dá", "deliver", "menghantar"],
    ["订户", "dìng hù", "customer", "pelanggan"],
    ["的", "de", "", ""],
    ["手上", "shǒu shàng", "hands", "tangan"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第7段

    // ===== 第7段 =====
    ["他", "tā", "He", "Dia"],
    ["深知", "shēn zhī", "deeply knows", "sangat tahu"],
    ["，", "", "", ""],
    ["准时", "zhǔn shí", "punctuality", "tepat masa"],
    ["是", "shì", "is", "ialah"],
    ["承诺", "chéng nuò", "promise", "janji"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第8段

    // ===== 第8段 =====
    ["可是", "kě shì", "But", "Tetapi"],
    ["偶尔", "ǒu ěr", "occasionally", "kadang-kadang"],
    ["因为", "yīn wèi", "because", "kerana"],
    ["身体", "shēn tǐ", "body", "badan"],
    ["状态", "zhuàng tài", "condition", "keadaan"],
    ["不佳", "bù jiā", "not well", "tidak sihat"],
    ["或", "huò", "or", "atau"],
    ["路况", "lù kuàng", "road conditions", "keadaan jalan"],
    ["而", "ér", "and", "dan"],
    ["延误", "yán wù", "delayed", "lewat"],
    ["，", "", "", ""],
    ["就", "jiù", "then", "lalu"],
    ["会", "huì", "will", "akan"],
    ["招来", "zhāo lái", "invite", "mengundang"],
    ["订户", "dìng hù", "customer", "pelanggan"],
    ["的", "de", "", ""],
    ["埋怨", "mán yuàn", "complaints", "aduan"],
    ["。", "", "", ""],
    ["他", "tā", "his", "dia"],
    ["满肚子", "mǎn dù zi", "full of", "penuh"],
    ["的", "de", "", ""],
    ["苦楚", "kǔ chǔ", "bitterness", "kepahitan"],
    ["，", "", "", ""],
    ["只能", "zhǐ néng", "can only", "hanya boleh"],
    ["化作", "huà zuò", "turn into", "bertukar menjadi"],
    ["一声", "yī shēng", "a", "satu"],
    ["叹息", "tàn xī", "sigh", "keluhan"],
    ["。", "", "", ""],
    ["他", "tā", "He", "Dia"],
    ["从不", "cóng bù", "never", "tidak pernah"],
    ["与", "yǔ", "with", "dengan"],
    ["人", "rén", "people", "orang"],
    ["争辩", "zhēng biàn", "argue", "berhujah"],
    ["——", "", "", ""],
    ["他", "tā", "he", "dia"],
    ["知道", "zhī dào", "knows", "tahu"],
    ["，", "", "", ""],
    ["对方", "duì fāng", "the other party", "pihak lain"],
    ["也许", "yě xǔ", "perhaps", "mungkin"],
    ["饿着肚子", "è zhe dù zi", "hungry", "lapar"],
    ["等", "děng", "waited", "menunggu"],
    ["了", "le", "", ""],
    ["很久", "hěn jiǔ", "very long", "sangat lama"],
    ["，", "", "", ""],
    ["心中", "xīn zhōng", "in heart", "dalam hati"],
    ["自然", "zì rán", "naturally", "secara semula jadi"],
    ["焦急", "jiāo jí", "anxious", "cemas"],
    ["。", "", "", ""],
    ["他", "tā", "He", "Dia"],
    ["只能", "zhǐ néng", "can only", "hanya boleh"],
    ["默默", "mò mò", "silently", "diam-diam"],
    ["低头", "dī tóu", "lower head", "menunduk"],
    ["，", "", "", ""],
    ["道歉", "dào qiàn", "apologise", "minta maaf"],
    ["，", "", "", ""],
    ["再", "zài", "then", "lalu"],
    ["赶去", "gǎn qù", "rush to", "bergegas ke"],
    ["下一单", "xià yī dān", "next order", "pesanan seterusnya"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第9段

    // ===== 第9段 =====
    ["他", "tā", "He", "Dia"],
    ["在", "zài", "in", "di"],
    ["风里雨里", "fēng lǐ yǔ lǐ", "in wind and rain", "dalam angin dan hujan"],
    ["，", "", "", ""],
    ["风尘仆仆", "fēng chén pú pú", "travel-worn", "lesu perjalanan"],
    ["。", "", "", ""],
    ["雨水", "yǔ shuǐ", "rainwater", "air hujan"],
    ["和", "hé", "and", "dan"],
    ["汗水", "hàn shuǐ", "sweat", "peluh"],
    ["混", "hùn", "mixed", "bercampur"],
    ["在", "zài", "in", "di"],
    ["一起", "yī qǐ", "together", "bersama"],
    ["，", "", "", ""],
    ["沿着", "yán zhe", "along", "sepanjang"],
    ["脸颊", "liǎn jiá", "cheeks", "pipi"],
    ["滑落", "huá luò", "slide down", "mengalir turun"],
    ["，", "", "", ""],
    ["他", "tā", "he", "dia"],
    ["分不清", "fēn bù qīng", "cannot tell", "tidak dapat membezakan"],
    ["是", "shì", "is", "ialah"],
    ["汗", "hàn", "sweat", "peluh"],
    ["是", "shì", "is", "ialah"],
    ["雨", "yǔ", "rain", "hujan"],
    ["，", "", "", ""],
    ["也", "yě", "also", "juga"],
    ["无暇", "wú xiá", "no time", "tiada masa"],
    ["擦拭", "cā shì", "wipe", "mengelap"],
    ["，", "", "", ""],
    ["只能", "zhǐ néng", "can only", "hanya boleh"],
    ["依旧", "yī jiù", "still", "masih"],
    ["抖擞精神", "dǒu sǒu jīng shén", "brace up", "membangkitkan semangat"],
    ["。", "", "", ""],
    ["尽管", "jǐn guǎn", "although", "walaupun"],
    ["容颜", "róng yán", "appearance", "rupa"],
    ["憔悴", "qiáo cuì", "haggard", "lesu"],
    ["了", "le", "", ""],
    ["，", "", "", ""],
    ["身心", "shēn xīn", "body and mind", "jasmani dan rohani"],
    ["疲惫", "pí bèi", "exhausted", "letih"],
    ["了", "le", "", ""],
    ["，", "", "", ""],
    ["他", "tā", "he", "dia"],
    ["也", "yě", "also", "juga"],
    ["要", "yào", "must", "perlu"],
    ["规矩", "guī jǔ", "properly", "dengan teratur"],
    ["地", "de", "", ""],
    ["履行", "lǚ xíng", "fulfil", "melaksanakan"],
    ["职责", "zhí zé", "duty", "tanggungjawab"],
    ["，", "", "", ""],
    ["继续", "jì xù", "continue", "meneruskan"],
    ["与", "yǔ", "with", "dengan"],
    ["时间", "shí jiān", "time", "masa"],
    ["追逐", "zhuī zhú", "chase", "mengejar"],
    ["这场", "zhè chǎng", "this", "ini"],
    ["漫长", "màn cháng", "long", "panjang"],
    ["的", "de", "", ""],
    ["游戏", "yóu xì", "game", "permainan"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第10段

    // ===== 第10段 =====
    ["但", "dàn", "But", "Tetapi"],
    ["生活中", "shēng huó zhōng", "in life", "dalam kehidupan"],
    ["，", "", "", ""],
    ["并非", "bìng fēi", "is not", "bukanlah"],
    ["只有", "zhǐ yǒu", "only", "hanya"],
    ["艰辛", "jiān xīn", "hardship", "kepayahan"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第11段

    // ===== 第11段 =====
    ["那天", "nà tiān", "That day", "Hari itu"],
    ["傍晚", "bàng wǎn", "evening", "waktu senja"],
    ["，", "", "", ""],
    ["他", "tā", "he", "dia"],
    ["冒着", "mào zhe", "braving", "menempuh"],
    ["大雨", "dà yǔ", "heavy rain", "hujan lebat"],
    ["，", "", "", ""],
    ["把", "bǎ", "", ""],
    ["一份", "yī fèn", "a", "satu"],
    ["暖意融融", "nuǎn yì róng róng", "warm", "hangat"],
    ["的", "de", "", ""],
    ["餐点", "cān diǎn", "meal", "makanan"],
    ["送到", "sòng dào", "delivered to", "dihantar ke"],
    ["一位", "yī wèi", "an", "seorang"],
    ["老奶奶", "lǎo nǎi nai", "grandmother", "nenek"],
    ["手中", "shǒu zhōng", "hands", "tangan"],
    ["。", "", "", ""],
    ["老奶奶", "lǎo nǎi nai", "grandmother", "nenek"],
    ["看", "kàn", "saw", "melihat"],
    ["他", "tā", "him", "dia"],
    ["浑身", "hún shēn", "whole body", "seluruh badan"],
    ["湿透", "shī tòu", "soaked", "basah kuyup"],
    ["，", "", "", ""],
    ["转身", "zhuǎn shēn", "turned around", "berpaling"],
    ["进屋", "jìn wū", "entered the house", "masuk ke rumah"],
    ["，", "", "", ""],
    ["拿出", "ná chū", "took out", "mengeluarkan"],
    ["一罐", "yī guàn", "a can", "satu tin"],
    ["沁人心脾", "qìn rén xīn pí", "refreshing", "menyegarkan"],
    ["的", "de", "", ""],
    ["饮料", "yǐn liào", "drink", "minuman"],
    ["递", "dì", "handed", "menghulurkan"],
    ["给", "gěi", "to", "kepada"],
    ["他", "tā", "him", "dia"],
    ["，", "", "", ""],
    ["轻声", "qīng shēng", "softly", "perlahan"],
    ["说", "shuō", "said", "berkata"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["孩子", "hái zi", "child", "anak"],
    ["，", "", "", ""],
    ["辛苦", "xīn kǔ", "hard work", "penat lelah"],
    ["了", "le", "", ""],
    ["，", "", "", ""],
    ["喝口", "hē kǒu", "drink a sip", "minum sedikit"],
    ["热水", "rè shuǐ", "hot water", "air panas"],
    ["吧", "ba", "", ""],
    ["。", "", "", ""],
    ["”", "", "", ""],

    ["\n", "", "", ""], // 👈 第12段

    // ===== 第12段 =====
    ["那", "nà", "That", "Itu"],
    ["一刻", "yī kè", "moment", "saat"],
    ["，", "", "", ""],
    ["他", "tā", "he", "dia"],
    ["愣", "lèng", "stunned", "terkejut"],
    ["在", "zài", "at", "di"],
    ["原地", "yuán dì", "original spot", "tempat asal"],
    ["，", "", "", ""],
    ["眼眶", "yǎn kuàng", "eye socket", "rongga mata"],
    ["发热", "fā rè", "warm", "panas"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第13段

    // ===== 第13段 =====
    ["一声声", "yī shēng shēng", "voice after voice", "suara demi suara"],
    ["真诚", "zhēn chéng", "sincere", "ikhlas"],
    ["的", "de", "", ""],
    ["道谢", "dào xiè", "thanks", "ucapan terima kasih"],
    ["，", "", "", ""],
    ["一次次", "yī cì cì", "time after time", "kali demi kali"],
    ["温暖", "wēn nuǎn", "warm", "hangat"],
    ["的", "de", "", ""],
    ["举动", "jǔ dòng", "gestures", "perbuatan"],
    ["，", "", "", ""],
    ["成", "chéng", "became", "menjadi"],
    ["了", "le", "", ""],
    ["他", "tā", "his", "dia"],
    ["奔波", "bēn bō", "rushing about", "berulang-alik"],
    ["路上", "lù shàng", "on the road", "di jalan"],
    ["最大", "zuì dà", "greatest", "terbesar"],
    ["的", "de", "", ""],
    ["慰藉", "wèi jiè", "comfort", "penghiburan"],
    ["。", "", "", ""],
    ["而", "ér", "and", "dan"],
    ["每天", "měi tiān", "every day", "setiap hari"],
    ["深夜", "shēn yè", "late night", "lewat malam"],
    ["回到家", "huí dào jiā", "returned home", "pulang ke rumah"],
    ["，", "", "", ""],
    ["看到", "kàn dào", "see", "melihat"],
    ["家人", "jiā rén", "family", "keluarga"],
    ["熟睡", "shú shuì", "sound asleep", "tidur nyenyak"],
    ["的", "de", "", ""],
    ["面容", "miàn róng", "faces", "wajah"],
    ["，", "", "", ""],
    ["感受", "gǎn shòu", "feel", "merasai"],
    ["到", "dào", "to", "ke"],
    ["妻子", "qī zi", "wife", "isteri"],
    ["贴心", "tiē xīn", "thoughtful", "prihatin"],
    ["的", "de", "", ""],
    ["关爱", "guān ài", "care", "kasih sayang"],
    ["，", "", "", ""],
    ["他", "tā", "he", "dia"],
    ["便", "biàn", "then", "lalu"],
    ["觉得", "jué de", "feel", "rasa"],
    ["一切", "yī qiè", "all", "segala"],
    ["辛苦", "xīn kǔ", "hardship", "kepayahan"],
    ["都", "dōu", "all", "semua"],
    ["有", "yǒu", "have", "ada"],
    ["了", "le", "", ""],
    ["意义", "yì yì", "meaning", "makna"],
    ["。", "", "", ""],
    ["这", "zhè", "this", "ini"],
    ["，", "", "", ""],
    ["就是", "jiù shì", "is", "adalah"],
    ["他", "tā", "he", "dia"],
    ["坚持", "jiān chí", "persist", "berterusan"],
    ["下去", "xià qù", "down", "ke bawah"],
    ["的", "de", "", ""],
    ["最大", "zuì dà", "greatest", "terbesar"],
    ["动力", "dòng lì", "motivation", "motivasi"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第14段

    // ===== 第14段 =====
    ["他", "tā", "He", "Dia"],
    ["渐渐", "jiàn jiàn", "gradually", "beransur-ansur"],
    ["明白", "míng bái", "understand", "faham"],
    ["，", "", "", ""],
    ["只要", "zhǐ yào", "as long as", "asalkan"],
    ["落寞", "luò mò", "loneliness", "kesunyian"],
    ["、", "", "", ""],
    ["徘徊", "pái huái", "hesitation", "keraguan"],
    ["、", "", "", ""],
    ["焦虑", "jiāo lǜ", "anxiety", "kebimbangan"],
    ["不复存在", "bù fù cún zài", "no longer exist", "tidak wujud lagi"],
    ["，", "", "", ""],
    ["他", "tā", "his", "dia"],
    ["奔驰", "bēn chí", "galloping", "berlari kencang"],
    ["于", "yú", "on", "di"],
    ["路上", "lù shàng", "road", "jalan"],
    ["的", "de", "", ""],
    ["汗水", "hàn shuǐ", "sweat", "peluh"],
    ["，", "", "", ""],
    ["就", "jiù", "will", "akan"],
    ["不会", "bù huì", "will not", "tidak akan"],
    ["白费", "bái fèi", "wasted", "sia-sia"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第15段

    // ===== 第15段 =====
    ["他", "tā", "He", "Dia"],
    ["祈愿", "qí yuàn", "prays", "berdoa"],
    ["人们", "rén men", "people", "orang ramai"],
    ["，", "", "", ""],
    ["因为", "yīn wèi", "because of", "kerana"],
    ["关怀", "guān huái", "care", "keprihatinan"],
    ["，", "", "", ""],
    ["彼此", "bǐ cǐ", "each other", "satu sama lain"],
    ["更", "gèng", "more", "lebih"],
    ["愿意", "yuàn yì", "willing", "sanggup"],
    ["释出", "shì chū", "release", "mengeluarkan"],
    ["善意", "shàn yì", "goodwill", "niat baik"],
    ["；", "", "", ""],
    ["因为", "yīn wèi", "because of", "kerana"],
    ["包容", "bāo róng", "tolerance", "toleransi"],
    ["，", "", "", ""],
    ["大家", "dà jiā", "everyone", "semua orang"],
    ["携手同心", "xié shǒu tóng xīn", "join hands", "berganding bahu"],
    ["，", "", "", ""],
    ["跨越", "kuà yuè", "cross over", "melangkaui"],
    ["焦躁", "jiāo zào", "impatience", "kegelisahan"],
    ["的", "de", "", ""],
    ["隔阂", "gé hé", "barrier", "jurang"],
    ["，", "", "", ""],
    ["一同", "yī tóng", "together", "bersama-sama"],
    ["迈向", "mài xiàng", "march towards", "menuju ke"],
    ["繁荣昌盛", "fán róng chāng shèng", "prosperous", "makmur"],
    ["、", "", "", ""],
    ["更具", "gèng jù", "more", "lebih"],
    ["同理心", "tóng lǐ xīn", "empathy", "empati"],
    ["的", "de", "", ""],
    ["社会", "shè huì", "society", "masyarakat"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第16段

    // ===== 第16段 =====
    ["他", "tā", "He", "Dia"],
    ["戴上", "dài shàng", "put on", "memakai"],
    ["头盔", "tóu kuī", "helmet", "topi keledar"],
    ["，", "", "", ""],
    ["再次", "zài cì", "again", "sekali lagi"],
    ["出发", "chū fā", "set off", "bertolak"],
    ["。", "", "", ""],
    ["风雨", "fēng yǔ", "wind and rain", "angin dan hujan"],
    ["依旧", "yī jiù", "still", "masih"],
    ["，", "", "", ""],
    ["但", "dàn", "but", "tetapi"],
    ["他", "tā", "his", "dia"],
    ["的", "de", "", ""],
    ["眼神", "yǎn shén", "gaze", "pandangan mata"],
    ["，", "", "", ""],
    ["比", "bǐ", "than", "daripada"],
    ["从前", "cóng qián", "before", "dahulu"],
    ["更", "gèng", "more", "lebih"],
    ["坚定", "jiān dìng", "firm", "teguh"],
    ["了", "le", "", ""],
    ["。", "", "", ""],
];

// 如果使用模块导出，取消下一行注释；若通过 script 标签引入，则全局可用
// export { lessonTitle, lessonData };
